import { createApp } from 'vue';
import App from './App.vue';
import './registerServiceWorker';
import PrimeVue from 'primevue/config';
import router from './infra/router';
import 'primevue/resources/themes/md-light-indigo/theme.css';
import 'primevue/resources/primevue.min.css';
import 'primeicons/primeicons.css';
const app = createApp(App);
app.use(router);
app.use(PrimeVue, { ripple: true });
app.mount('#app');
